// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6PxeMCjD93EHsrihk_5zbz0cSG5Er7KY',
    appId: '1:772675378330:web:d571cac604d79d62425323',
    messagingSenderId: '772675378330',
    projectId: 'otpproject-77266',
    authDomain: 'otpproject-77266.firebaseapp.com',
    storageBucket: 'otpproject-77266.firebasestorage.app',
    measurementId: 'G-VTHZQHVQ9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADIq0VJvC9kd-SzP_nyHHo0VXT4QAo8o',
    appId: '1:772675378330:android:e0dd996313f7223b425323',
    messagingSenderId: '772675378330',
    projectId: 'otpproject-77266',
    storageBucket: 'otpproject-77266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPlBAiAYIA4kErTCJGGRe-QaCZvcchtOI',
    appId: '1:772675378330:ios:09c6b27debf72702425323',
    messagingSenderId: '772675378330',
    projectId: 'otpproject-77266',
    storageBucket: 'otpproject-77266.firebasestorage.app',
    iosBundleId: 'com.example.otpVerificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPlBAiAYIA4kErTCJGGRe-QaCZvcchtOI',
    appId: '1:772675378330:ios:09c6b27debf72702425323',
    messagingSenderId: '772675378330',
    projectId: 'otpproject-77266',
    storageBucket: 'otpproject-77266.firebasestorage.app',
    iosBundleId: 'com.example.otpVerificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6PxeMCjD93EHsrihk_5zbz0cSG5Er7KY',
    appId: '1:772675378330:web:2d1ee53f43f845d3425323',
    messagingSenderId: '772675378330',
    projectId: 'otpproject-77266',
    authDomain: 'otpproject-77266.firebaseapp.com',
    storageBucket: 'otpproject-77266.firebasestorage.app',
    measurementId: 'G-R6K5DGGPQQ',
  );
}
